# Generated by Django 4.0.5 on 2022-09-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('snipet', models.TextField()),
            ],
        ),
    ]
