# Generated by Django 4.0.5 on 2022-09-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_elements_element'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='snipet',
            new_name='snippet',
        ),
    ]
